language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8
  - oraclejdk10
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
branches:
  only:
    - master
