language: scala
scala:
  - 2.12.10
  - 2.13.1
jdk:
  - oraclejdk11
  - openjdk8
  - openjdk11
script: 
  - sbt ++$TRAVIS_SCALA_VERSION clean compile test
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.sbt -name "*.lock" | xargs rm -f
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm -f
branches:
  only:
    - master
