name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '13' ]
        scala: [ '2.13.10' ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{matrix.java}}
          cache: sbt
    - name: print Java version
      run: java -version
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - name: setup apibuilder config
      run: mkdir ~/.apibuilder && echo "[default]" > ~/.apibuilder/config
    - name: Build
      run: sbt ++${{ matrix.scala }} clean test
